language: java
jdk:
  - oraclejdk17
dist: xenial
before_install:
  - chmod +x mvnw
  - sudo service postgresql@13-main restart
addons:
  postgresql: 13
  apt:
    update: true
    packages:
      - postgresql-13
      - postgresql-13-postgis-3
services:
  - postgresql
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
    - PGHOST=localhost
before_script:
  - psql -c 'create database "Library-API";' -U postgres