language: java
jdk:
  - oraclejdk17
dist: trusty
before_install:
  - chmod +x mvnw
addons:
  postgresql: '13'
  apt:
    packages:
      - postgresql-13
env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=root
    - PGPORT=5432
    - PGHOST=localhost
script:
  - psql -c 'create database "Library-API";' -U postgres