language: java
jdk:
  - oraclejdk17
dist: xenial
before_install:
  - chmod +x mvnw
addons:
  postgresql: 13
  apt:
    update: true
    packages:
      - postgresql-13
      - postgresql-13-postgis-3
services:
  - postgresql
env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=root
    - PGPORT=5432
before_script:
  - psql -c 'CREATE DATABASE "Library-API";' -U postgres -p 5432