language: java
jdk:
  - oraclejdk17
dist: trusty
before_install:
  - chmod +x mvnw
services:
  - postgresql
addons:
  postgresql: 13
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
      - libpq-dev
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - clang-tidy
before_script:
  - psql -c 'create database "Library-API";' -U postgres
env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=root
    - PGPORT=5432