language: java
jdk:
  - oraclejdk17
dist: trusty
before_install:
  - chmod +x mvnw
services:
  - postgresql
env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=root
    - PGPORT=5432
before_script:
  - psql -c 'CREATE DATABASE "Library-API";' -U postgres -p 5432