language: java
jdk:
  - oraclejdk17
dist: trusty
before_install:
  - chmod +x mvnw
services:
  - postgresql
before_script:
  - psql -c 'create database Library-API;' -U postgres
env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=root
    - PGPORT=5432