version: "3.8"

services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Library-API
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      ms-net:
    restart: on-failure

  libray-api:
    container_name: library-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      ms-net:
    restart: on-failure

networks:
  ms-net:
    driver: bridge