spring:
  application:
    name: library-api

  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: # Your email
    password: # Your email password
    properties:
      mail:
        tls: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp-mail.outlook.com

app:
  mail:
    late-loans:
      message: Attention! You have a book overdue. Please return it as soon as possible or request a new loan.
    default-mailSender: # Your email again

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: appFile.log
