version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: Library-API
        command: /bin/sh
    working_directory: /app

    steps:
      - checkout

      # Instalar o Maven
      - run:
          name: Install Maven
          command: |
            wget -q https://apache.osuosl.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
            tar xf apache-maven-3.8.4-bin.tar.gz
            export PATH=$PWD/apache-maven-3.8.4/bin:$PATH

      # Aqui você pode adicionar os comandos para construir e testar sua aplicação Maven
      - run:
          name: Build and Test
          command: |
            mvn clean install
            mvn test
